project:
  type: website

website:
  title: "Benjamin Wee"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/bennywee
      - icon: twitter
        href: https://twitter.com/BenwWee
      - icon: linkedin
        href: https://www.linkedin.com/in/benjamin-wee3
format:
  html:
    theme: flatly
    css: styles.css



