---
title: Master's presentation to Adelaide data science group
author: "Benjamin Wee"
date: 2025-04-24
engine: knitr
pdf: "presentation.pdf"
---

Master's research presentation on stochastic volatility and simulation based calibration to the Adelaide data science group on November 2023.

# Abstract

Simulation Based Calibration (SBC) (Talts, Betancourt, Simpson, Vehtari, & Gelman, 2020) is applied to analyse two commonly used, competing Markov chain Monte Carlo algorithms for estimating the posterior distribution of a stochastic volatility model. In particular, the bespoke ‘off-set mixture approximation’ algorithm proposed by Kim, Shephard, and Chib (1998) is explored together with a Hamiltonian Monte Carlo algorithm implemented through Stan (Stan Development Team, 2023). The SBC analysis involves a simulation study to assess whether each sampling algorithm has the capacity to produce valid inference for the correctly specified model, while also characterising statistical efficiency through the effective sample size. Results show that Stan’s No-U-Turn sampler, an implementation of Hamiltonian Monte Carlo, produces a well-calibrated posterior estimate while the celebrated off-set mixture approach is less efficient and poorly calibrated, though model parameterisation also plays a role.

```{css, echo=FALSE}
#title-block-header .description {
    display: none;
}
```

```{css echo=FALSE}
.embed-container {
    position: relative;
    padding-bottom: 129%;
    height: 0;
    overflow: hidden;
    max-width: 100%;
}

.embed-container iframe,
.embed-container object,
.embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```{=html}
<div class="embed-container">
  <iframe src="`r rmarkdown::metadata$pdf`" style="border: 0.5px"></iframe>
</div>
```